#aws_region           = "eu-central-1"                 # Change this to your desired AWS region
project_name         = "wordpress-boilerplate"        # Change this to your desired project name
vpc_cidr             = "10.0.0.0/16"                  # Change this to your desired VPC CIDR
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.3.0/24"] # Change this to your desired public subnet CIDR
private_subnet_cidrs = ["10.0.2.0/24", "10.0.4.0/24"] # Change this to your desired private subnet CIDR
instance_type        = "t2.micro"                     # Change this to your desired instance type
instance_count       = "2"                            # Change this to the number of instances you want
key_pair_name        = "bastion-ssh-key"              # Change this to your key pair name
allowed_ssh_cidr     = "0.0.0.0/0"                    # Change this to your IP
db_engine            = "mysql"                        # Change this to your desired DB engine
db_instance_class    = "db.t3.micro"                  # Change this to your desired DB instance class
db_storage           = "20"                           # Change this to your desired DB storage size
db_retention         = "7"                            # Change this to your desired DB retention period
db_name              = "your_db_name"                 # Change this to your desired DB name
public_key_path      = "~/.ssh/ansible.pub"           # Change this to your public key path
db_username          = "your_db_username"             # Change this to your desired DB username
db_password          = "your_secure_db_password"      # Change this to your desired DB password
