- name: Install PHP and dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php
    - libapache2-mod-php
    - php-mysql

- name: Restart Apache
  service:
    name: apache2
    state: restarted